{"name": "test_vs_login[kyle-123456-kyle1]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './image/err.png'", "trace": "self = <scripts.test_vs_login.TestVsLogin object at 0x000002DC0DB9D5F8>\nusername = 'kyle', password = '123456', expect = 'kyle1'\n\n    @pytest.mark.parametrize(\"username,password,expect\", read_yaml(\"vs_login.yaml\"))\n    def test_vs_login(self, username, password, expect):\n        self.vs.page_vs_login(username, password)\n        # print(\"The nickname obtained is:\", self.vs.page_get_nickname())\n        process_before = self.vs.page_get_nickname()\n        process_later = process_before.strip()\n        try:\n>           assert expect == process_later\nE           AssertionError: assert 'kyle1' == 'kyle'\n\ntest_vs_login.py:33: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test_vs_login.TestVsLogin object at 0x000002DC0DB9D5F8>\nusername = 'kyle', password = '123456', expect = 'kyle1'\n\n    @pytest.mark.parametrize(\"username,password,expect\", read_yaml(\"vs_login.yaml\"))\n    def test_vs_login(self, username, password, expect):\n        self.vs.page_vs_login(username, password)\n        # print(\"The nickname obtained is:\", self.vs.page_get_nickname())\n        process_before = self.vs.page_get_nickname()\n        process_later = process_before.strip()\n        try:\n            assert expect == process_later\n        except Exception as e:\n            log.error(\"断言出错，错误信息：{}\".format(e))\n            print(\"断言出错，错误信息：\", e)\n>           self.vs.base_get_img()\n\ntest_vs_login.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\base\\base.py:70: in base_get_img\n    self.__base_write_img()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.page_vs_login.PageVsLogin object at 0x000002DC0DBF4048>\n\n    def __base_write_img(self):\n>       with open(\"./image/err.png\", \"rb\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: './image/err.png'\n\n..\\base\\base.py:74: FileNotFoundError"}, "steps": [{"name": "one step", "status": "passed", "parameters": [{"name": "username", "value": "'kyle'"}], "start": 1633951159472, "stop": 1633951159516}, {"name": "two step", "status": "passed", "parameters": [{"name": "password", "value": "'123456'"}], "start": 1633951159516, "stop": 1633951159570}, {"name": "three step", "status": "passed", "start": 1633951159570, "stop": 1633951160366}, {"name": "four step", "status": "passed", "start": 1633951160366, "stop": 1633951160728}], "attachments": [{"name": "log", "source": "298e7d85-1cb2-4fb3-acde-31b0443b552c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'kyle'"}, {"name": "password", "value": "'123456'"}, {"name": "expect", "value": "'kyle1'"}], "start": 1633951159472, "stop": 1633951160835, "uuid": "2c33ead0-9f3d-45e7-aa42-57ae0afa4e97", "historyId": "76244b16e28a27bc103aa37d645a0ded", "testCaseId": "a862348e7f0264acaa54055b030ba7d5", "fullName": "scripts.test_vs_login.TestVsLogin#test_vs_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_vs_login"}, {"name": "subSuite", "value": "TestVsLogin"}, {"name": "host", "value": "LAPTOP-2MM4SIL7"}, {"name": "thread", "value": "25524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_vs_login"}]}